import pandas as pd
import numpy as np
from datetime import datetime
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

start_time = datetime.now()
print("Script start:", start_time.strftime("%H:%M:%S"))


# Read in prepared csv that is generated by prepare_data.py
df = pd.read_csv(
    'data/prepared/output.csv',
    sep=',',
    decimal='.',
    parse_dates=['date']
)

# Set the datetime column as the index
df.set_index('date', inplace=True)

columns_to_sum = ['pv_cost_save', 'grid_cost', 'bat_discharge_win', 'bat_charge_cost']

# Group by month and sum only the specified columns
monthly_sums = df[columns_to_sum].resample('ME').sum()

# Print the monthly sums for the specified columns
print(monthly_sums)
